<?php
/**
 * Lightweight on-page SEO: meta description, Open Graph, Twitter Card, and
 * sitewide Organization/WebSite structured data.
 *
 * No SEO plugin (Yoast/Rank Math) is active on this site, so the theme owns
 * these tags directly. Product-level structured data is generated by
 * WooCommerce core (see woocommerce/single-product.php).
 *
 * @package WM_Theme
 */

defined( 'ABSPATH' ) || exit;

/**
 * Build a plain-text excerpt for use as a meta description.
 *
 * @param string $text   Source text (may contain HTML/shortcodes).
 * @param int    $length Max character length.
 * @return string
 */
function wm_seo_truncate_description( $text, $length = 160 ) {
	$text = wp_strip_all_tags( strip_shortcodes( (string) $text ) );
	$text = trim( preg_replace( '/\s+/u', ' ', $text ) );

	if ( '' === $text ) {
		return '';
	}

	$current_length = function_exists( 'mb_strlen' ) ? mb_strlen( $text ) : strlen( $text );

	if ( $current_length > $length ) {
		$text = function_exists( 'mb_substr' ) ? mb_substr( $text, 0, $length - 1 ) : substr( $text, 0, $length - 1 );
		$text .= '…';
	}

	return $text;
}

/**
 * Resolve the meta description for the current request.
 *
 * @return string
 */
function wm_seo_get_description() {
	if ( function_exists( 'is_product' ) && is_product() ) {
		$product = function_exists( 'wm_get_current_product' ) ? wm_get_current_product() : null;
		if ( $product ) {
			$source = $product->get_short_description();
			if ( '' === trim( wp_strip_all_tags( $source ) ) ) {
				$source = $product->get_description();
			}
			$description = wm_seo_truncate_description( $source );
			if ( $description ) {
				return $description;
			}
		}
	}

	if ( is_singular() ) {
		$post = get_queried_object();
		if ( $post instanceof WP_Post ) {
			$source      = $post->post_excerpt ? $post->post_excerpt : $post->post_content;
			$description = wm_seo_truncate_description( $source );
			if ( $description ) {
				return $description;
			}
		}
	}

	if ( is_tax() || is_category() || is_tag() ) {
		$description = wm_seo_truncate_description( term_description() );
		if ( $description ) {
			return $description;
		}
	}

	if ( function_exists( 'is_shop' ) && is_shop() ) {
		$shop_page_id = function_exists( 'wc_get_page_id' ) ? wc_get_page_id( 'shop' ) : 0;
		if ( $shop_page_id > 0 ) {
			$description = wm_seo_truncate_description( get_post_field( 'post_content', $shop_page_id ) );
			if ( $description ) {
				return $description;
			}
		}
	}

	return wm_seo_truncate_description( get_bloginfo( 'description' ) );
}

/**
 * Resolve the share image URL for the current request (OG/Twitter).
 *
 * @return string
 */
function wm_seo_get_image_url() {
	if ( function_exists( 'is_product' ) && is_product() ) {
		$product = function_exists( 'wm_get_current_product' ) ? wm_get_current_product() : null;
		if ( $product ) {
			$image_id = $product->get_image_id();
			if ( $image_id ) {
				$url = wp_get_attachment_image_url( $image_id, 'large' );
				if ( $url ) {
					return $url;
				}
			}
		}
	}

	if ( is_singular() && has_post_thumbnail() ) {
		$url = get_the_post_thumbnail_url( get_queried_object_id(), 'large' );
		if ( $url ) {
			return $url;
		}
	}

	if ( has_custom_logo() ) {
		$logo_id  = get_theme_mod( 'custom_logo' );
		$logo_url = $logo_id ? wp_get_attachment_image_url( $logo_id, 'large' ) : '';
		if ( $logo_url ) {
			return $logo_url;
		}
	}

	return '';
}

/**
 * Output <meta name="description">, Open Graph, and Twitter Card tags in <head>.
 */
function wm_seo_render_meta_tags() {
	if ( is_admin() ) {
		return;
	}

	$description = wm_seo_get_description();
	$title       = wp_get_document_title();
	$url         = wp_get_canonical_url();
	if ( ! $url ) {
		$url = home_url( add_query_arg( null, null ) );
	}
	$image       = wm_seo_get_image_url();
	$site_name   = get_bloginfo( 'name' );
	$og_type     = is_singular() ? 'article' : 'website';

	if ( function_exists( 'is_product' ) && is_product() ) {
		$og_type = 'product';
	}

	if ( $description ) {
		printf( '<meta name="description" content="%s">' . "\n", esc_attr( $description ) );
	}

	printf( '<meta property="og:type" content="%s">' . "\n", esc_attr( $og_type ) );
	printf( '<meta property="og:title" content="%s">' . "\n", esc_attr( $title ) );
	if ( $description ) {
		printf( '<meta property="og:description" content="%s">' . "\n", esc_attr( $description ) );
	}
	printf( '<meta property="og:url" content="%s">' . "\n", esc_url( $url ) );
	printf( '<meta property="og:site_name" content="%s">' . "\n", esc_attr( $site_name ) );
	if ( $image ) {
		printf( '<meta property="og:image" content="%s">' . "\n", esc_url( $image ) );
	}

	printf( '<meta name="twitter:card" content="%s">' . "\n", esc_attr( $image ? 'summary_large_image' : 'summary' ) );
	printf( '<meta name="twitter:title" content="%s">' . "\n", esc_attr( $title ) );
	if ( $description ) {
		printf( '<meta name="twitter:description" content="%s">' . "\n", esc_attr( $description ) );
	}
	if ( $image ) {
		printf( '<meta name="twitter:image" content="%s">' . "\n", esc_url( $image ) );
	}
}
add_action( 'wp_head', 'wm_seo_render_meta_tags', 1 );

/**
 * Output sitewide Organization + WebSite JSON-LD structured data.
 */
function wm_seo_render_site_structured_data() {
	if ( is_admin() ) {
		return;
	}

	$logo_url = '';
	if ( has_custom_logo() ) {
		$logo_id  = get_theme_mod( 'custom_logo' );
		$logo_url = $logo_id ? wp_get_attachment_image_url( $logo_id, 'full' ) : '';
	}

	$organization = array(
		'@context' => 'https://schema.org',
		'@type'    => 'Organization',
		'name'     => get_bloginfo( 'name' ),
		'url'      => home_url( '/' ),
	);

	if ( $logo_url ) {
		$organization['logo'] = $logo_url;
	}

	$website = array(
		'@context' => 'https://schema.org',
		'@type'    => 'WebSite',
		'name'     => get_bloginfo( 'name' ),
		'url'      => home_url( '/' ),
		'potentialAction' => array(
			'@type'       => 'SearchAction',
			'target'      => home_url( '/?s={search_term_string}' ),
			'query-input' => 'required name=search_term_string',
		),
	);

	printf( '<script type="application/ld+json">%s</script>' . "\n", wp_json_encode( $organization ) );
	printf( '<script type="application/ld+json">%s</script>' . "\n", wp_json_encode( $website ) );
}
add_action( 'wp_head', 'wm_seo_render_site_structured_data', 2 );
